
export const CollisionTag = Object.freeze({
  Default: "default",
  Player: "player",
  MapObject: "mapobject",
  Road: "road",
  upHillRoad: "uphillroad",
  UpHillLowRoad: "upHillLowRoad",
  downHillRoad: "downhillroad",
    downHillLowRoad: "downhillLowroad",
  bumpyRoad: "bumpyroad",
  EndWall: "endwall",
  BigBossStart: "bigbossstart",
  SoliderBossStart: "soliderbossstart",
  Boss: "boss",
  FinishLine: "finishline",
  SoliderPlayer: "solider:player",
  SoliderEnemy: "solider:enemy",
  HeadWall: "wall",
  BodyWall: "bodywall",
  RedDamage: "reddamage",
  Jump: "jump",
  SawBlade: "sawblade",
  item: "item",
  item_lose: "item_lose",
  the_face: "the_face",
  endRoad: "endroad",
  hand_left: "hand_left",
  itemBurger: "itemBurger",
  man: "man",
  endRoad2: "endRoad2",
  endRoad1: "endRoad1",
  table: "table",
  fork: "fork",
  hob: "hob",
  hammer: "hammer",
  knife: "knife",
  Door: "Door",
  curvedUp: "cu",
  curvedDown: "cd",
  RollingDough:"RollingDough",
  turnLeft:'left',
  turnRight:'right',
  ignoreTurn:"ig",
  turnAround:'around',
  win:'win',
  barier:'barier'
});
