
export const ObjectType = Object.freeze({
  NONE: "none",
  ROAD: "ra",
  FallObstacle: "fo",
  UPHILL: "uh",
  DOWNHILL: "dh",
  DOWNHILLLOW: "dl",
  BUMPYROAD: "br",
  WALL: "wall",
  NUMBER: "number",
  FINISH_LINE: "finishLine",
  RED_DAMAGE: "redDamage",
  MATH_WALL: "mathWall",
  JUMP: "jump",
  SAW_BLADE: "sawBlade",
  SAW_BLADE_MOVE: "sawBladeMove",
  END_WALL: "endWall",
  SALAD: "s",
  CHESSE: "c",
  SHIT: "Shit",
  HOTDOG: "hd",
  ONION: "o",
  JUMPSTATE: "j",
  JUMPSTATE2: "j2",
  HANDLEFT: "hl",
  THEFACE: "tf",
  ENDROAD2: "er2",
  ANOTHERBURGER: "ab",
  man: 'm',
  table: 'tb',
  endRoad1: 'er1',
  endRoad0: 'er0',
  hob: 'h',
  fork: 'f',
  hand_right: 'hr',
  hammer: "ham",
    RollingDough: "RollingDough",

  UPHILLLOW: "ul",
  GIAN: 'gian',
  HOLE: 'hole',
  KNIFE: "knife",
  DOORDECOR: "DoorDecor",
  CURVEDUP: "cu",
  CURVEDDOWN: "cd"
});